# Generated by Django 5.1.3 on 2024-11-30 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        ('sellers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(default='Selling', max_length=30)),
                ('pet_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(max_length=15)),
                ('age', models.PositiveBigIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_sold_or_adopted', models.BooleanField(default=False)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pets.petbreed')),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pets.pet')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='sellers.seller')),
            ],
        ),
        migrations.CreateModel(
            name='PetListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pet_listing_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.petlisting')),
            ],
        ),
        migrations.CreateModel(
            name='PetListingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=15)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pet_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='posts.petlisting')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes_count', models.PositiveBigIntegerField(default=0)),
                ('comment_count', models.PositiveBigIntegerField(default=0)),
                ('shares_count', models.PositiveBigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.post')),
            ],
        ),
    ]
