# Generated by Django 5.1.3 on 2024-12-26 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_petlisting_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petlistinglocation',
            old_name='location_name',
            new_name='address',
        ),
    ]
