# Generated by Django 5.1.3 on 2024-12-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_location_name_petlistinglocation_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetListingImageTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redis_key', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='pet_listing_images_temp/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
