# Generated by Django 5.1.3 on 2024-12-30 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_petlistingimagetemp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petlistingimagetemp',
            name='redis_key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
