# Generated by Django 5.1.3 on 2024-12-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_petlistingimagetemp_redis_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petlistingimagetemp',
            name='redis_key',
            field=models.CharField(max_length=255),
        ),
    ]
