# Generated by Django 5.1.3 on 2024-12-30 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_petlistingimagetemp_redis_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petlistinglocation',
            name='pet_listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='posts.petlisting'),
        ),
    ]
