# Generated by Django 5.1.3 on 2025-01-07 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_comment_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
