# Generated by Django 5.1.3 on 2025-01-07 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_like_post_remove_like_user_delete_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes_count',
            new_name='like_count',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='shares_count',
            new_name='save_count',
        ),
    ]
