# Generated by Django 5.1.3 on 2025-01-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_rename_likes_count_post_like_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hide_comments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='hide_likes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='turn_off_comments',
            field=models.BooleanField(default=False),
        ),
    ]
