# Generated by Django 5.1.3 on 2025-03-07 11:05

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_savedpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petlistingimage',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='pet_listing_images/'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='post_images/'),
        ),
    ]
