# Generated by Django 5.1.3 on 2025-03-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_petlistingimage_image_alter_postimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petlistingimage',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
