# Generated by Django 5.1.3 on 2025-03-14 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_petlistingimage_image_alter_postimage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PetListingImageTemp',
        ),
    ]
