# Generated by Django 5.1.3 on 2024-12-19 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petbreed',
            name='icon',
        ),
    ]
