# Generated by Django 5.1.3 on 2025-03-07 11:05

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_remove_petbreed_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='icon',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='pet_type_icons/'),
        ),
    ]
