# Generated by Django 5.1.3 on 2025-03-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='icon',
            field=models.URLField(blank=True, null=True),
        ),
    ]
