# Generated by Django 5.1.3 on 2025-01-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsettings',
            name='is_deactivate',
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
