# Generated by Django 5.1.3 on 2025-01-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_accountsettings_is_deactivate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petsphereuser',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
