# Generated by Django 5.1.3 on 2025-01-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_petsphereuser_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petsphereuser',
            name='slug',
        ),
    ]
