# Generated by Django 5.1.3 on 2025-01-28 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_petsphereuser_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsettings',
            name='is_private',
        ),
    ]
