# Generated by Django 5.1.3 on 2024-11-30 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
