# Generated by Django 5.1.3 on 2024-12-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_emailotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petsphereuser',
            name='profile_picture',
        ),
    ]
