# Generated by Django 5.1.3 on 2025-03-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='reported_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
