# Generated by Django 5.1.3 on 2025-03-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_reports_reported_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='type',
            field=models.CharField(choices=[('user', 'User'), ('listing', 'Listing'), ('post', 'Post')], max_length=20),
        ),
    ]
