# Generated by Django 5.1.3 on 2024-11-26 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cover_pics/')),
                ('is_private', models.BooleanField(default=False)),
                ('push_notification', models.BooleanField(default=False)),
                ('follower_count', models.PositiveBigIntegerField(default=0)),
                ('following_count', models.PositiveBigIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
