# Generated by Django 5.1.3 on 2025-01-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_profile_pawstory_count_profile_petlisting_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='free_posts',
            field=models.PositiveBigIntegerField(default=3),
        ),
    ]
