# Generated by Django 5.1.3 on 2025-01-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_profile_free_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='IsSubscribed',
            field=models.BooleanField(default=False),
        ),
    ]
