# Generated by Django 5.1.3 on 2025-01-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_profile_issubscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='IsSeller',
            field=models.BooleanField(default=False),
        ),
    ]
