# Generated by Django 5.1.3 on 2025-01-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_profile_isseller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(blank=True, default='default_images/profile_cover.svg', null=True, upload_to='cover_pics/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_images/user_avatar.svg', null=True, upload_to='profile_pics/'),
        ),
    ]
