# Generated by Django 5.1.3 on 2025-02-10 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_alter_profile_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_private',
        ),
    ]
