# Generated by Django 5.1.3 on 2025-03-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_remove_profile_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='push_notification',
            field=models.BooleanField(default=True),
        ),
    ]
