# Generated by Django 5.1.3 on 2025-01-30 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
