# Generated by Django 5.1.3 on 2025-02-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='unread_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
