# Generated by Django 5.1.3 on 2025-02-08 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_conversation_last_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='unread_count',
        ),
    ]
