# Generated by Django 5.1.3 on 2025-03-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_message_media_file_message_message_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='media_file',
        ),
        migrations.AddField(
            model_name='message',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
