# Generated by Django 5.1.3 on 2024-11-18 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petsphereuser',
            name='created_at',
        ),
    ]
