# Generated by Django 5.1.3 on 2024-11-26 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_cover_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
