# Generated by Django 5.1.3 on 2025-02-18 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcements',
            name='publishing_date',
        ),
    ]
