# Generated by Django 5.1.3 on 2025-03-07 11:05

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_remove_announcements_publishing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='icon',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='accouncements/icon/'),
        ),
    ]
